
import numpy as np
from scipy import ndimage as ndi
from skimage import feature, segmentation, morphology, measure

def get_peaks(raw:np.ndarray,mask1:np.ndarray,mask2:np.ndarray,
              alpha: float=1.5,min_dist:float=4,min_size:int=27):

    filtered = raw[(mask1 > 0)]


    print("min_size, mean int, std int",min_size,filtered.min(),filtered.mean(),filtered.std(),filtered.max())
    try:
        threshold = filtered.mean() + alpha * filtered.std()

    except:
        print(raw[mask1>0].shape,raw[mask2>0].shape,raw[(mask1 > 0) & (mask2 > 0)].shape)
        threshold = 0


    foci_mask = np.zeros_like(raw,dtype=bool)
    foci_mask[(raw > threshold) & (mask1>0) & (mask2 > 0)] = True
    print("foci mask pre-filt",foci_mask[foci_mask==True].shape)

    # Identify local intensity maxima
    coords = feature.peak_local_max(raw, min_distance=min_dist,labels=foci_mask)
    peak_mask = np.zeros(raw.shape, dtype=bool)
    peak_mask[tuple(coords.T)] = True
    markers, _ = ndi.label(peak_mask)


    # Watershed segment the images using the local maxima
    labels = segmentation.watershed(-raw, markers, mask=foci_mask)
    labels = morphology.remove_small_objects(labels, min_size=min_size)
    labels = measure.label(labels).astype(np.int32, copy=False)
    final_coords = feature.peak_local_max(raw, min_distance=1,labels=labels,num_peaks_per_label=1)

    print(alpha,markers.shape,len(np.unique(labels[labels>0])),final_coords.shape)

    return labels,final_coords








def gen_mask_erosion(binary_image,ib,nbins,maxdistxy,maxdistz=None):

    """
    Generate masks by progressively eroding from the spheroid.
    Parameters:
    binary_image (numpy.ndarray): A 2D binary image where the spheroid is represented by non-zero values.
    nbins (int): Number of bins or masks to generate.
    maxdistxy (float): Maximum distance in the xy-plane for erosion.
    maxdistz (float): Maximum distance in the z-plane for erosion.
    Returns:
    tuple: A tuple containing:
        - masks (numpy.ndarray): An array of shape (nbins, binary_image.shape[0], binary_image.shape[1])
            containing the masks generated by erosion.
        - bins_dr (numpy.ndarray): An array of bin distances used for erosion.
    """

    #### get masks by progressively eroding from the spheroid
    # masks = np.zeros((nbins,) + binary_image.shape, np.int64)
    mask = np.zeros(binary_image.shape, np.int64)
    drxy = maxdistxy/nbins
    boundary_shell_xy = int(drxy)
    # drz = maxdistz/nbins
    # boundary_shell_z = max(1,int(0.25*drxy)) #int(drz)


    bins_dr = np.array([(i+0.5) for i in range(nbins)])

    #### need to do checking if bulk still exists, else masks is empty
    bw = binary_image > 0


    for i in range(ib+1):
        bulk = np.array([],np.int64)

        if bw.ndim == 3:
            bulk = np.copy(bw)
            for z in range(bw.shape[0]):
                bulk[z] = morphology.binary_erosion(bw[z],
                            morphology.square(boundary_shell_xy))
        if bw.ndim == 2:
            bulk = morphology.binary_erosion(bw,
                            morphology.square(boundary_shell_xy))


        if bulk[bulk > 0].size > 0:
            shell = np.subtract(bw * 1, bulk * 1) ## true in bw and subtract the eroded part
            bw = np.copy(bulk)
            if i == ib:
                mask = np.copy(shell)
            # masks[i] = np.copy(shell)

        else:
            ## nothing left
            if i == ib:
                mask = np.zeros_like(binary_image,np.int64)
            # masks[i] = np.zeros_like(binary_image,np.int64)
            ## dont update bw and dont calculate shell

    # print("erosion masks",masks.shape,np.unique(masks))
    return mask,bins_dr


def gen_mask_expand(binary_image,ib,nbins,maxdistxy,maxdistz=None):

    # masks = np.zeros((nbins,) + binary_image.shape, np.int64)
    mask = np.zeros(binary_image.shape, np.int64)
    drxy = maxdistxy/nbins
    boundary_shell_xy = int(drxy)
    # drz = maxdistz/nbins
    # boundary_shell_z = max(1,int(0.25*drxy))
    bins_dr = np.array([(i+0.5) for i in range(nbins)])

    #### need to do checking if bulk still exists, else masks is empty
    bw = binary_image > 0

    # if bw.ndim == 3:
    #     expansion = np.zeros_like(bw)
    #     for z in range(bw.shape[0]):
    #         expansion[z] = ndi.binary_dilation(bw[z],
    #                                             structure=np.ones((boundary_shell_xy,
    #                                                                 boundary_shell_xy)),
    #                                                                   iterations=ib + 1)
    # else:
    #     expansion = ndi.binary_dilation(bw,
    #                                      structure=np.ones((boundary_shell_xy,
    #                                                             boundary_shell_xy)),
    #                                                               iterations=ib + 1)

    # shell = expansion & ~bw
    # mask = shell.astype(np.int64)

    # # print("expansion masks", mask.shape, np.unique(mask))
    # return mask, bins_dr


    for i in range(ib+1):

        expansion = np.copy(bw)
        if bw.ndim == 3:
            for z in range(bw.shape[0]):
                expansion[z] = segmentation.expand_labels(bw[z],distance=boundary_shell_xy)
        else:
            expansion = segmentation.expand_labels(bw,distance=boundary_shell_xy)

        shell = np.subtract(expansion * 1, bw *1)
        if i == ib:
            mask = np.copy(shell)
        # masks[i] = np.copy(shell)

        bw = np.copy(expansion)

    print("expansion masks",mask.shape,np.unique(mask))
    return mask,bins_dr




def gen_mask_fast(binary_image,cenx,ceny,nbins,maxdist):

    masks = np.zeros((nbins,) + binary_image.shape, np.int64)
    dr = maxdist / nbins
    bins_dr = np.array([(i+0.5) for i in range(nbins)])
    binary = np.ones_like(binary_image)
    binary[int(ceny),int(cenx)] = 0


    if binary.ndim == 2:
        distance = ndi.distance_transform_edt(binary)
    else:
        distance = ndi.distance_transform_edt(binary, sampling=(1, 1, 1))

    for i in range(nbins):
        dist_min = i * dr
        dist_max = (i + 1) * dr
        masks[i] = (distance >= dist_min) & (distance < dist_max)

    print("radial masks", masks.shape, np.unique(masks))
    return masks, bins_dr
